In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [2]:
import numpy as np

In [3]:
!pip install numpy

In [4]:
np.__version__

'1.19.5'

In [5]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
a[2:5]

array([3, 4, 5])

In [8]:
np.size(a)

10

In [9]:
np.shape(a)

(10,)

In [10]:
sorted(a , reverse=True)

[10, 9, 8, 7, 6, 5, 4, 3, 2, 1]

In [6]:
b = np.array([[1,2,3] , [4,5,6] , [7,8,9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
b[:,0]

array([1, 4, 7])

In [14]:
np.size(b,1)

3

In [15]:
b.ndim

2

In [16]:
np_mix_matrix = np.array([['one',2],['three',4],['five',6]])
np_mix_matrix

array([['one', '2'],
       ['three', '4'],
       ['five', '6']], dtype='<U5')

In [19]:
np.array(np_mix_matrix[:,1], dtype = int)

array([2, 4, 6])

In [20]:
c = np.zeros((5,5))
c

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [24]:
d = np.ones((10))
d

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [28]:
e = np.full((3,3),7)
e

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [30]:
f = np.eye(2)
f

array([[1., 0.],
       [0., 1.]])

In [31]:
np.sqrt(np.full((2,2),4))

array([[2., 2.],
       [2., 2.]])

In [35]:
np.round(np.random.rand()*10)

3.0

In [45]:
np.random.randint(5)

3

In [48]:
np.random.choice(a,5, replace=False)

array([ 7,  6,  8, 10,  1])

In [70]:
np_matrix = np.round(np.random.rand(1000,5))
np_matrix

array([[1., 1., 1., 0., 1.],
       [1., 0., 1., 0., 0.],
       [1., 1., 1., 0., 0.],
       ...,
       [0., 0., 0., 1., 1.],
       [1., 1., 1., 1., 0.],
       [0., 1., 1., 0., 1.]])

In [50]:
idx_choose = np.random.choice(1000,100, replace=False)
idx_choose

array([401, 367, 808,  14, 673, 746, 602, 756, 867, 240, 163, 314, 249,
       242, 965, 130, 813, 899, 628, 771, 585, 400, 556, 422, 214, 427,
       593, 302, 268, 539, 848, 901, 152, 447, 436, 764, 940, 933, 823,
        28,  50, 690, 895, 618, 236,  76, 732, 751, 730,  26, 475, 429,
       830,  30, 935, 907, 252, 959, 107, 179, 106, 594, 815, 979, 291,
       653, 167, 217, 804, 444, 926, 989, 381, 661, 560, 519,  16, 255,
       762, 550, 105, 332, 900, 869,  83, 567,  34, 705, 490, 784,  66,
       786, 506, 311, 981, 966, 177, 139, 223,  75])

In [51]:
np_matrix_choose = np_matrix[idx_choose,:]
np_matrix_choose

array([[0., 1., 0., 0., 1.],
       [1., 0., 1., 1., 0.],
       [0., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 0., 0., 1.],
       [0., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0.],
       [0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [1., 0., 0., 1., 0.],
       [1., 0., 0., 1., 1.],
       [1., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1.],
       [0., 1., 0., 0., 1.],
       [0., 0., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [0., 1., 0., 0., 1.],
       [0., 0., 1., 1., 1.],
       [0., 1., 1., 1., 1.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 1.],
       [1., 0., 1., 0., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 1., 0., 1.],
       [1., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0.],
       [1., 0., 0., 1., 0.],
       [1., 1., 0., 1., 1.],
       [0., 1., 1., 1., 0.],
       [0., 0., 1., 0., 0.],
       [0., 1., 1., 0., 1.],
       [0., 0.

In [71]:
np_matrix = np.random.randint(3,size = (5,5))
np_matrix

array([[1, 2, 0, 0, 1],
       [0, 0, 2, 2, 2],
       [2, 2, 2, 2, 1],
       [2, 0, 1, 0, 2],
       [1, 2, 2, 1, 2]])

In [75]:
row,column = np.where(np_matrix == 2)
[(row[i],column[i]) for i in range(len(row))]

[(0, 1),
 (1, 2),
 (1, 3),
 (1, 4),
 (2, 0),
 (2, 1),
 (2, 2),
 (2, 3),
 (3, 0),
 (3, 4),
 (4, 1),
 (4, 2),
 (4, 4)]

In [80]:
rng= np.random.RandomState(0)
np_matrix = rng.randint(3,size = (5,5))
np_matrix

array([[0, 1, 0, 1, 1],
       [2, 0, 2, 0, 0],
       [0, 2, 1, 2, 2],
       [0, 1, 1, 1, 1],
       [0, 1, 0, 0, 1]])

In [10]:
#Ex 4
rng = np.random.RandomState(777)
matrix = rng.randint(10 ,size=(10,5))
matrix

array([[7, 6, 7, 1, 7],
       [4, 7, 9, 8, 7],
       [2, 0, 1, 2, 4],
       [5, 7, 1, 7, 2],
       [2, 7, 4, 8, 6],
       [2, 7, 8, 0, 8],
       [3, 2, 0, 3, 3],
       [4, 0, 6, 5, 7],
       [5, 5, 8, 1, 4],
       [7, 4, 4, 0, 9]])

In [11]:
rng = np.random.RandomState(777)
vertor = rng.randint(2, size=10)
vertor

array([1, 1, 1, 0, 1, 1, 1, 1, 1, 0])

In [12]:
matrix[np.where(vertor==0)]

array([[5, 7, 1, 7, 2],
       [7, 4, 4, 0, 9]])

In [13]:
matrix[np.where(vertor==1)]

array([[7, 6, 7, 1, 7],
       [4, 7, 9, 8, 7],
       [2, 0, 1, 2, 4],
       [2, 7, 4, 8, 6],
       [2, 7, 8, 0, 8],
       [3, 2, 0, 3, 3],
       [4, 0, 6, 5, 7],
       [5, 5, 8, 1, 4]])